const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { blank } = require('../electron/storage.cjs');
const { exportCurrent } = require('../scripts/export-current-shared.cjs');

test('current public export follows local additions, preserves publisher and never writes private data', t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'gym-current-export-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const source = path.join(root, 'personal');
  const destination = path.join(root, 'public');
  fs.mkdirSync(path.join(source, 'database'), { recursive: true });
  fs.mkdirSync(path.join(source, 'equipment'));
  const file = path.join(source, 'database/data.json');
  const db = blank();
  db.equipment.push({ id: 'one', name: 'First', brandId: db.brands[0].id, equipmentType: 'cardio', image: 'equipment/first.png', notes: 'PRIVATE' });
  db.settings.secret = 'PRIVATE';
  fs.writeFileSync(path.join(source, 'equipment/first.png'), Buffer.from([137, 80, 78, 71]));
  fs.writeFileSync(file, JSON.stringify(db));
  exportCurrent(source, destination);
  const identity = JSON.parse(fs.readFileSync(path.join(destination, 'manifest.json'))).sourceId;
  db.equipment.push({ id: 'two', name: 'Second', brandId: db.brands[0].id, equipmentType: 'cardio', notes: 'PRIVATE' });
  const original = JSON.stringify(db);
  fs.writeFileSync(file, original);
  const result = exportCurrent(source, destination);
  assert.deepEqual(result.counts.equipment, { current: 2, previous: 1 });
  assert.equal(result.sourceUnchanged, true);
  assert.equal(result.images, 1);
  assert.equal(fs.readFileSync(file, 'utf8'), original);
  assert.equal(JSON.parse(fs.readFileSync(path.join(destination, 'manifest.json'))).sourceId, identity);
  assert.ok(!fs.readFileSync(path.join(destination, 'catalog.json'), 'utf8').includes('PRIVATE'));
  assert.deepEqual(fs.readFileSync(path.join(destination, 'images/equipment/first.png')), fs.readFileSync(path.join(source, 'equipment/first.png')));
  const before = fs.readFileSync(path.join(destination, 'catalog.json'));
  db.equipment[0].image = 'equipment/missing.png';
  fs.writeFileSync(file, JSON.stringify(db));
  assert.throws(() => exportCurrent(source, destination), /ENOENT/);
  assert.deepEqual(fs.readFileSync(path.join(destination, 'catalog.json')), before);
});
