const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { Store, hash } = require('../electron/storage.cjs');
const { exportShared, createSharedCatalog } = require('../electron/shared-catalog.cjs');
function fixture(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'gym-shared-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const publisher = new Store(path.join(root, 'publisher.json'));
  const subscriber = new Store(path.join(root, 'subscriber.json'));
  publisher.configure(path.join(root, 'source'));
  subscriber.configure(path.join(root, 'target'));
  const db = structuredClone(publisher.db);
  db.gyms.push({ id: 'gym1', name: 'Public gym', city: '上海', lat: null, lng: null, visited: true, visitDate: '2026-01-01', description: 'PRIVATE', notes: 'PRIVATE', reviewUrl: 'https://private.test', brandIds: ['brand-1'], cover: 'gyms/cover.png', photos: [] });
  db.equipment.push({ id: 'eq1', name: 'Bike', brandId: 'brand-1', equipmentType: 'cardio', parts: [], tags: [], notes: 'PRIVATE', image: '' });
  db.links.push({ id: 'link1', gymId: 'gym1', equipmentId: 'eq1', quantity: 2 });
  publisher.save(db);
  fs.mkdirSync(path.join(publisher.root, 'gyms'));
  fs.writeFileSync(path.join(publisher.root, 'gyms/cover.png'), Buffer.from([137, 80, 78, 71, 1]));
  const destination = path.join(root, 'public');
  const publish = () => exportShared(publisher, { destination, includeImages: true });
  publish();
  const fetcher = async url => fs.readFileSync(path.join(destination, new URL(url).pathname.replace('/repo/', '')));
  const api = createSharedCatalog(subscriber, fetcher);
  const preview = () => api.sharedPreview({ url: 'https://example.test/repo/manifest.json' });
  return { publisher, subscriber, destination, publish, api, preview };
}
test('custom parts and series share with alias normalization and protect local series edits', async t => {
  const {publisher,subscriber,publish,preview,api,destination}=fixture(t);
  const {upsert}=require('../electron/catalog.cjs');
  upsert(publisher,'equipment',{...publisher.db.equipment[0],equipmentType:'fixed',parts:['CUSTOM: 颈部 '],tags:[],series:' Alpha '});
  publish();const publicData=JSON.parse(fs.readFileSync(path.join(destination,'catalog.json')));
  assert.equal(publicData.equipment[0].series,'Alpha');
  let p=await preview();await api.sharedApply({token:p.token});let local=subscriber.db.equipment[0];
  assert.deepEqual(local.parts,['CUSTOM:颈部']);assert.equal(local.series,'Alpha');
  upsert(subscriber,'equipment',{...local,series:'Personal'});
  upsert(publisher,'equipment',{...publisher.db.equipment[0],series:'Beta'});publish();
  p=await preview();assert.ok(p.conflicts.some(c=>c.field==='series'));await api.sharedApply({token:p.token});
  assert.equal(subscriber.db.equipment[0].series,'Personal');
  const {checkCatalog}=require('../electron/shared-catalog.cjs');
  publicData.equipment[0].parts=['SHOULDER'];publicData.equipment[0].tags=['推肩'];
  assert.deepEqual(checkCatalog(publicData).equipment[0].tags,['肩推']);
});
test('brand logos share, cache, update and preserve a subscriber replacement', async t => {
  const { publisher, subscriber, destination, publish, api, preview } = fixture(t);
  const { saveImage, upsert } = require('../electron/catalog.cjs');
  const png = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10, 1]);
  const first = saveImage(publisher, png, 'brands');
  upsert(publisher, 'brands', { ...publisher.db.brands[0], logo: first });
  publish();
  let draft = await preview();
  await api.sharedApply({ token: draft.token });
  const local = subscriber.db.brands.find(b => b.name === publisher.db.brands[0].name);
  assert.match(local.logo, /^brands\/shared-/);
  assert.deepEqual(fs.readFileSync(path.join(subscriber.root, local.logo)), png);
  assert.equal((await preview()).downloadImages, 0);
  const replacement = saveImage(publisher, Buffer.concat([png, Buffer.from('new')]), 'brands');
  upsert(publisher, 'brands', { ...publisher.db.brands[0], logo: replacement });
  publish(); draft = await preview(); await api.sharedApply({ token: draft.token });
  assert.notEqual(subscriber.db.brands.find(b => b.id === local.id).logo, local.logo);
  const personal = saveImage(subscriber, Buffer.concat([png, Buffer.from('local')]), 'brands');
  upsert(subscriber, 'brands', { ...subscriber.db.brands.find(b => b.id === local.id), logo: personal });
  upsert(publisher, 'brands', { ...publisher.db.brands[0], logo: first });
  publish(); draft = await preview();
  assert.ok(draft.conflicts.some(c => c.field === 'logo'));
  await api.sharedApply({ token: draft.token });
  assert.equal(subscriber.db.brands.find(b => b.id === local.id).logo, personal);
  exportShared(publisher, { destination, includeImages: false });
  assert.equal(JSON.parse(fs.readFileSync(path.join(destination, 'catalog.json'))).brands[0].logo, undefined);
  assert.ok(!fs.existsSync(path.join(destination, 'images', first)));
});
test('public export omits personal fields and only packages referenced images', t => {
  const { destination, publisher } = fixture(t);
  const text = fs.readFileSync(path.join(destination, 'catalog.json'), 'utf8');
  assert.ok(!text.includes('PRIVATE'));
  for (const name of ['visited', 'visitDate', 'description', 'reviewUrl', 'notes', 'settings']) assert.ok(!text.includes(`"${name}"`));
  const manifest = JSON.parse(fs.readFileSync(path.join(destination, 'manifest.json')));
  assert.equal(manifest.images.length, 1);
  assert.equal(manifest.catalog.sha256, hash(Buffer.from(text)));
  assert.throws(() => exportShared(publisher, { destination: publisher.root }), /重叠/);
});
test('image sharing is opt-in and disabling removes previously exported image files', t => {
  const { destination, publisher } = fixture(t);
  exportShared(publisher, { destination });
  const data = JSON.parse(fs.readFileSync(path.join(destination, 'catalog.json')));
  assert.equal(data.gyms[0].cover, undefined);
  assert.ok(!fs.existsSync(path.join(destination, 'images/gyms/cover.png')));
});
test('preview does not write; confirmed subscription maps ids and preserves three-way local changes', async t => {
  const { publisher, subscriber, publish, api, preview } = fixture(t);
  const before = JSON.stringify(subscriber.db);
  let draft = await preview();
  assert.equal(JSON.stringify(subscriber.db), before);
  assert.equal(draft.counts.added, 3);
  await api.sharedApply({ token: draft.token });
  const localId = subscriber.db.gyms[0].id;
  assert.notEqual(localId, 'gym1');
  assert.equal(subscriber.db.gyms[0].visited, false);
  assert.equal(subscriber.db.brands.length, 19);
  let db = structuredClone(subscriber.db);
  db.gyms[0].visited = true; db.gyms[0].description = 'personal'; db.gyms[0].name = 'local edit';
  subscriber.save(db);
  db = structuredClone(publisher.db);
  db.gyms[0].name = 'remote edit'; db.gyms[0].city = '北京';
  publisher.save(db); publish();
  draft = await preview();
  assert.ok(draft.counts.conflicts >= 1);
  await api.sharedApply({ token: draft.token });
  assert.equal(subscriber.db.gyms[0].name, 'local edit');
  assert.equal(subscriber.db.gyms[0].city, '北京');
  assert.equal(subscriber.db.gyms[0].description, 'personal');
  assert.equal(subscriber.db.gyms[0].visited, true);
  assert.equal(subscriber.db.gyms[0].id, localId);
  draft = await preview();
  assert.equal(draft.counts.added, 0);
});
test('hash mismatch and unsafe paths never modify subscriber', async t => {
  const { subscriber, destination, preview } = fixture(t);
  const before = JSON.stringify(subscriber.db);
  fs.appendFileSync(path.join(destination, 'catalog.json'), ' ');
  await assert.rejects(preview(), /校验失败/);
  assert.equal(JSON.stringify(subscriber.db), before);
  const manifestFile = path.join(destination, 'manifest.json');
  const manifest = JSON.parse(fs.readFileSync(manifestFile));
  manifest.catalog.path = '../private.json';
  fs.writeFileSync(manifestFile, JSON.stringify(manifest));
  await assert.rejects(preview(), /格式无效/);
});
test('local changes invalidate pending preview and backup failure does not apply', async t => {
  const { subscriber, api, preview } = fixture(t);
  let draft = await preview();
  subscriber.save({ ...subscriber.db, settings: { changed: true } });
  await assert.rejects(api.sharedApply({ token: draft.token }), /本地数据已变化/);
  draft = await preview();
  subscriber.backup = async () => { throw new Error('backup failed'); };
  await assert.rejects(api.sharedApply({ token: draft.token }), /backup failed/);
  assert.equal(subscriber.db.gyms.length, 0);
});
test('upstream deletion retains subscriber data and subscriptions persist through restart', async t => {
  const { publisher, subscriber, publish, api, preview } = fixture(t);
  const draft = await preview(); await api.sharedApply({ token: draft.token });
  const restarted = new Store(subscriber.configFile);
  assert.equal(Object.keys(restarted.db.metadata.sharedCatalogs).length, 1);
  publisher.save({ ...publisher.db, gyms: [], links: [] }); publish();
  const next = await preview(); await api.sharedApply({ token: next.token });
  assert.equal(subscriber.db.gyms.length, 1);
  assert.equal(subscriber.db.links.length, 1);
});
test('existing hash-matched images are reused and failed database save rolls new images back', async t => {
  const { subscriber, api, preview } = fixture(t);
  let draft = await preview();
  assert.equal(draft.downloadImages, 1);
  const save = subscriber.save.bind(subscriber);
  subscriber.save = () => { throw new Error('disk full'); };
  await assert.rejects(api.sharedApply({ token: draft.token }), /disk full/);
  assert.equal(subscriber.db.gyms.length, 0);
  assert.equal(fs.readdirSync(path.join(subscriber.root, 'gyms')).length, 0);
  subscriber.save = save;
  draft = await preview(); await api.sharedApply({ token: draft.token });
  draft = await preview();
  assert.equal(draft.images, 1);
  assert.equal(draft.downloadImages, 0);
});
test('publisher subscribes to its own shared catalog without duplicating original records', async t => {
  const { publisher, destination } = fixture(t);
  const api = createSharedCatalog(publisher, async url => fs.readFileSync(path.join(destination, new URL(url).pathname.replace('/repo/', ''))));
  const draft = await api.sharedPreview({ url: 'https://example.test/repo/manifest.json' });
  assert.equal(draft.counts.added, 0);
  await api.sharedApply({ token: draft.token });
  assert.equal(publisher.db.gyms.length, 1);
  assert.equal(publisher.db.equipment.length, 1);
  assert.equal(publisher.db.links.length, 1);
  assert.equal(publisher.db.settings.sharedCatalogUrl, 'https://example.test/repo/manifest.json');
  assert.ok(publisher.db.settings.sharedLastSyncedAt);
});
test('classification merges as one unit when local and publisher change different classification fields', async t => {
  const { publisher, subscriber, publish, api, preview } = fixture(t);
  let db = structuredClone(publisher.db);
  Object.assign(db.equipment[0], { equipmentType: 'fixed', parts: ['CHEST'], part: 'CHEST', tags: ['推胸'], loading: '' });
  publisher.save(db); publish();
  let draft = await preview(); await api.sharedApply({ token: draft.token });
  db = structuredClone(subscriber.db);
  Object.assign(db.equipment[0], { equipmentType: 'free_weight', freeWeightType: 'dumbbell', parts: [], part: '', tags: [], loading: '' });
  subscriber.save(db);
  db = structuredClone(publisher.db); db.equipment[0].tags.push('夹胸');
  publisher.save(db); publish();
  draft = await preview();
  assert.ok(draft.conflicts.some(c => c.field === 'classification'));
  await api.sharedApply({ token: draft.token });
  assert.equal(subscriber.db.equipment[0].equipmentType, 'free_weight');
  assert.equal(subscriber.db.equipment[0].freeWeightType, 'dumbbell');
  assert.deepEqual(subscriber.db.equipment[0].parts, []);
  assert.deepEqual(subscriber.db.equipment[0].tags, []);
});
test('existing export directory retains publisher identity and rejects different publishers', t => {
  const { publisher, destination } = fixture(t);
  const originalId = publisher.db.metadata.sharedPublisherId;
  const db = structuredClone(publisher.db); delete db.metadata.sharedPublisherId;
  publisher.save(db);
  assert.equal(exportShared(publisher, { destination }).sourceId, originalId);
  assert.equal(publisher.db.metadata.sharedPublisherId, originalId);
  publisher.save({ ...publisher.db, metadata: { ...publisher.db.metadata, sharedPublisherId: 'another-publisher' } });
  assert.throws(() => exportShared(publisher, { destination }), /其他共享库/);
  assert.equal(JSON.parse(fs.readFileSync(path.join(destination, 'manifest.json'))).sourceId, originalId);
});
